In [92]:
import pandas as pd
data_ratings = pd.read_csv("u.data" , sep="\t",header = None)
data_ratings.columns = ["user id" ,"item id", "rating", "timestamp"]

data_ratings.head()

col_names = ["Movie id","Movie Name", "Release Date","Video release date", "Website", "Unknown", "Action",  "Adventure", "Animation"
             ,"Children's", "Comedy", "Crime", "Documentary","Drama","Fantasy","Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi"
              ,"Thriller","War" ,"Western"]

data_item = pd.read_csv('u.item',names = col_names, sep='|',encoding='latin-1')
data_item

#data_item.set_index('Movie id', inplace=True)

data_item = data_item.drop(["Video release date","Unknown"], axis=1)

data_item = data_item.drop("Website",axis=1)

data_item.head()

Movie id         Movie Name Release Date  Action  Adventure  Animation  \
0         1   Toy Story (1995)  01-Jan-1995       0          0          1   
1         2   GoldenEye (1995)  01-Jan-1995       1          1          0   
2         3  Four Rooms (1995)  01-Jan-1995       0          0          0   
3         4  Get Shorty (1995)  01-Jan-1995       1          0          0   
4         5     Copycat (1995)  01-Jan-1995       0          0          0   

   Children's  Comedy  Crime  Documentary  ...  Fantasy  Film-Noir  Horror  \
0           1       1      0            0  ...        0          0       0   
1           0       0      0            0  ...        0          0       0   
2           0       0      0            0  ...        0          0       0   
3           0       1      0            0  ...        0          0       0   
4           0       0      1            0  ...        0          0       0   

   Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western  
0        0        0        0       0         0    0        0  
1        0        0        0       0         1    0        0  
2        0        0        0       0         1    0        0  
3        0        0        0       0         0    0        0  
4        0        0        0       0         1    0        0  

[5 rows x 21 columns]

In [93]:
data_ratings.head()

user id  item id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [94]:
import numpy as np

In [95]:
data_ratings_np = data_ratings.to_numpy()
data_item_np = data_item.to_numpy()

In [96]:
type(data_ratings_np)

numpy.ndarray

In [97]:
type(data_item_np)

numpy.ndarray

In [98]:
list(data_ratings_np)

[array([      196,       242,         3, 881250949]),
 array([      186,       302,         3, 891717742]),
 array([       22,       377,         1, 878887116]),
 array([      244,        51,         2, 880606923]),
 array([      166,       346,         1, 886397596]),
 array([      298,       474,         4, 884182806]),
 array([      115,       265,         2, 881171488]),
 array([      253,       465,         5, 891628467]),
 array([      305,       451,         3, 886324817]),
 array([        6,        86,         3, 883603013]),
 array([       62,       257,         2, 879372434]),
 array([      286,      1014,         5, 879781125]),
 array([      200,       222,         5, 876042340]),
 array([      210,        40,         3, 891035994]),
 array([      224,        29,         3, 888104457]),
 array([      303,       785,         3, 879485318]),
 array([      122,       387,         5, 879270459]),
 array([      194,       274,         2, 879539794]),
 array([      291,      1042

In [99]:
list(data_item_np)

[array([1, 'Toy Story (1995)', '01-Jan-1995', 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0], dtype=object),
 array([2, 'GoldenEye (1995)', '01-Jan-1995', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0], dtype=object),
 array([3, 'Four Rooms (1995)', '01-Jan-1995', 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=object),
 array([4, 'Get Shorty (1995)', '01-Jan-1995', 1, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object),
 array([5, 'Copycat (1995)', '01-Jan-1995', 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0], dtype=object),
 array([6, 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
        '01-Jan-1995', 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0], dtype=object),
 array([7, 'Twelve Monkeys (1995)', '01-Jan-1995', 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=object),
 array([8, 'Babe (1995)', '01-Jan-1995', 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
        0